--
-- PostgreSQL database dump
--

\restrict RggHMA7Z7mjQ5IDFIZwh5mAWgsFMAZWISuMcJK5l8l9CShjit80cudWYviia0rg

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-21 19:00:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 32819)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id integer NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32818)
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 32824)
-- Name: catalogo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalogo (
    id integer NOT NULL,
    quantidade_de_filmes integer,
    data_entrada date,
    data_saida date
);


ALTER TABLE public.catalogo OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32823)
-- Name: catalogo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalogo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 32828)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id_usuario integer NOT NULL,
    forma_de_pagamento character varying(100),
    planos_id integer NOT NULL
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 32832)
-- Name: cliente_filme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente_filme (
    cliente_id integer NOT NULL,
    filme_id integer NOT NULL,
    historico character varying(500)
);


ALTER TABLE public.cliente_filme OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 32838)
-- Name: filmes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.filmes (
    id integer NOT NULL,
    sinopse character varying(255),
    duracao character varying(100),
    titulo character varying(100),
    ano_de_lancamento integer,
    equipe character varying(255),
    genero_id integer,
    catalogo_id integer NOT NULL
);


ALTER TABLE public.filmes OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 32837)
-- Name: filmes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.filmes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.filmes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 32814)
-- Name: genero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genero (
    id integer NOT NULL,
    tipo character varying(100),
    descricao character varying(500),
    catalogo_id integer
);


ALTER TABLE public.genero OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32813)
-- Name: genero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genero ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 32846)
-- Name: planos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.planos (
    id integer NOT NULL,
    nome character varying(100),
    duracao character varying(100),
    preco numeric(10,2),
    numero_de_telas integer,
    qualidade character varying(50),
    anuncios integer
);


ALTER TABLE public.planos OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 32845)
-- Name: planos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.planos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 32851)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    nome character varying(100),
    senha character varying(255),
    ddd integer,
    numero integer
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 32850)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5063 (class 0 OID 32819)
-- Dependencies: 222
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin (id, id_usuario) FROM stdin;
\.


--
-- TOC entry 5065 (class 0 OID 32824)
-- Dependencies: 224
-- Data for Name: catalogo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalogo (id, quantidade_de_filmes, data_entrada, data_saida) FROM stdin;
1	100	2025-06-01	2027-06-01
\.


--
-- TOC entry 5066 (class 0 OID 32828)
-- Dependencies: 225
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id_usuario, forma_de_pagamento, planos_id) FROM stdin;
1	crédito	2
\.


--
-- TOC entry 5067 (class 0 OID 32832)
-- Dependencies: 226
-- Data for Name: cliente_filme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente_filme (cliente_id, filme_id, historico) FROM stdin;
\.


--
-- TOC entry 5069 (class 0 OID 32838)
-- Dependencies: 228
-- Data for Name: filmes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.filmes (id, sinopse, duracao, titulo, ano_de_lancamento, equipe, genero_id, catalogo_id) FROM stdin;
2	Um ladrão especializado invade sonhos para roubar informações.	2h 28min	A Origem	2010	Christopher Nolan	1	1
3	Um parasita alienígena transforma um jornalista em anti-herói.	1h 52min	Venom	2018	Ruben Fleischer	1	1
4	Uma aventura épica em um mundo habitado por dinossauros clonados.	2h 04min	Jurassic World	2015	Colin Trevorrow	1	1
5	Um programador descobre que vive dentro de uma simulação.	2h 16min	Matrix	1999	Lana Wachowski, Lilly Wachowski	1	1
6	teste	100	teste	2026	direção teste	1	1
7	teste	100	teste	2026	direção teste	1	1
8	Uma hacker descobre uma conspiração global dentro de uma plataforma de streaming.	135	Código Invisível	2025	Direção: Maria Souza	1	1
\.


--
-- TOC entry 5061 (class 0 OID 32814)
-- Dependencies: 220
-- Data for Name: genero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genero (id, tipo, descricao, catalogo_id) FROM stdin;
1	ação	gênero cinematográfico em que os conflitos são resolvidos sobretudo por meio de lutas, cenas de violência e perseguições	1
\.


--
-- TOC entry 5071 (class 0 OID 32846)
-- Dependencies: 230
-- Data for Name: planos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.planos (id, nome, duracao, preco, numero_de_telas, qualidade, anuncios) FROM stdin;
1	basico	ilimitado	0.00	1	1080p	3
2	premium	1 mes	30.00	3	2040p	6
\.


--
-- TOC entry 5073 (class 0 OID 32851)
-- Dependencies: 232
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, nome, senha, ddd, numero) FROM stdin;
1	cayky	senha123	85	986444305
\.


--
-- TOC entry 5079 (class 0 OID 0)
-- Dependencies: 221
-- Name: admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_id_seq', 1, false);


--
-- TOC entry 5080 (class 0 OID 0)
-- Dependencies: 223
-- Name: catalogo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalogo_id_seq', 1, true);


--
-- TOC entry 5081 (class 0 OID 0)
-- Dependencies: 227
-- Name: filmes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.filmes_id_seq', 9, true);


--
-- TOC entry 5082 (class 0 OID 0)
-- Dependencies: 219
-- Name: genero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genero_id_seq', 1, true);


--
-- TOC entry 5083 (class 0 OID 0)
-- Dependencies: 229
-- Name: planos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.planos_id_seq', 2, true);


--
-- TOC entry 5084 (class 0 OID 0)
-- Dependencies: 231
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, true);


--
-- TOC entry 4892 (class 2606 OID 32870)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id, id_usuario);


--
-- TOC entry 4894 (class 2606 OID 32858)
-- Name: catalogo catalogo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalogo
    ADD CONSTRAINT catalogo_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 32874)
-- Name: cliente_filme cliente_filme_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente_filme
    ADD CONSTRAINT cliente_filme_pkey PRIMARY KEY (cliente_id, filme_id);


--
-- TOC entry 4896 (class 2606 OID 32865)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 4900 (class 2606 OID 32867)
-- Name: filmes filmes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filmes
    ADD CONSTRAINT filmes_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 32856)
-- Name: genero genero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genero
    ADD CONSTRAINT genero_pkey PRIMARY KEY (id);


--
-- TOC entry 4902 (class 2606 OID 32860)
-- Name: planos planos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.planos
    ADD CONSTRAINT planos_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 32862)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 32880)
-- Name: admin admin_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4909 (class 2606 OID 32895)
-- Name: cliente_filme cliente_filme_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente_filme
    ADD CONSTRAINT cliente_filme_cliente_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4910 (class 2606 OID 32900)
-- Name: cliente_filme cliente_filme_filme_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente_filme
    ADD CONSTRAINT cliente_filme_filme_fkey FOREIGN KEY (filme_id) REFERENCES public.filmes(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4907 (class 2606 OID 32890)
-- Name: cliente cliente_planos_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_planos_fkey FOREIGN KEY (planos_id) REFERENCES public.planos(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4908 (class 2606 OID 32885)
-- Name: cliente cliente_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4911 (class 2606 OID 32910)
-- Name: filmes filmes_catalogo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filmes
    ADD CONSTRAINT filmes_catalogo_fkey FOREIGN KEY (catalogo_id) REFERENCES public.catalogo(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4912 (class 2606 OID 32905)
-- Name: filmes filmes_genero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.filmes
    ADD CONSTRAINT filmes_genero_fkey FOREIGN KEY (genero_id) REFERENCES public.genero(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4905 (class 2606 OID 32875)
-- Name: genero genero_catalogo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genero
    ADD CONSTRAINT genero_catalogo_fkey FOREIGN KEY (catalogo_id) REFERENCES public.catalogo(id) ON UPDATE CASCADE ON DELETE RESTRICT;


-- Completed on 2026-06-21 19:00:51

--
-- PostgreSQL database dump complete
--

\unrestrict RggHMA7Z7mjQ5IDFIZwh5mAWgsFMAZWISuMcJK5l8l9CShjit80cudWYviia0rg

